### ISSUE TITLE
🚨 Renaming the role breaks every usage

### ISSUE THREAD

**Issue by FrankGiesecke** [mrlesmithjr/ansible-avahi#6]
@mrlesmithjr you have renamed the role on galaxy from `mrlesmithjr.avahi` to `mrlesmithjr.ansible_avahi`.
This breaks every project that is using your role 😢 .

In my case, I've a requirements file which is used in the CI to install all necessary roles and collections.  
Now this is breaking because of:
```
- downloading role 'avahi', owned by mrlesmithjr
[WARNING]: - mrlesmithjr.avahi was NOT installed successfully: - sorry,
mrlesmithjr.avahi was not found on https://galaxy.ansible.com/api/.
```

**Comment by mrlesmithjr** [comment]
@FrankGiesecke - Thank you for catching this. It should be fixed now.

**Comment by FrankGiesecke** [comment]
@mrlesmithjr Please, can you check your other roles too? I've seen, that all your role in galaxy have the `ansible_` or `ansible-` prefix.
